mod day1;
mod day2;
mod day3;
mod day4;
mod day5;
mod day6;
mod day7;
mod day8;
mod day9;
mod day10;
mod day11;
pub(crate) use day1::*;
pub(crate) use day2::*;
pub(crate) use day3::*;
pub(crate) use day4::*;
pub(crate) use day5::*;
pub(crate) use day6::*;
pub(crate) use day7::*;
pub(crate) use day8::*;
pub(crate) use day9::*;
pub(crate) use day10::*;
pub(crate) use day11::*;
